const crypto = require('crypto');
const db = require('../db');
const nowIso = () => new Date().toISOString();
const uid = () => crypto.randomUUID();
const fail = (code,status=400) => { const e=new Error(code); e.status=status; throw e; };
const text = (v,max=120) => typeof v==='string' && v.length<=max && !/[\p{Cc}\p{Cf}]/u.test(v) ? v.trim() : fail('invalid_text');
const integer = (v,min,max) => Number.isInteger(v)&&v>=min&&v<=max?v:fail('invalid_number');
const phone = v => { const n=String(v||'').replace(/[ ()-]/g,'').replace(/^\+/,''); const p=/^0\d{9}$/.test(n)?'27'+n.slice(1):n; return /^[1-9]\d{6,14}$/.test(p)?p:fail('invalid_phone'); };
const email = v => { if (!v) return ''; const s=text(v,254).toLowerCase(); return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)?s:fail('invalid_email'); };
const bool = v => typeof v==='boolean'?Number(v):fail('invalid_boolean');
const key = v => typeof v==='string'&&/^[A-Za-z0-9_-]{8,120}$/.test(v)?v:fail('invalid_idempotency_key');
const fingerprint = v => crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const booking = () => require('../booking');
function isModular(id) { return !!db.prepare('SELECT client_id FROM salon_settings WHERE client_id=?').get(id); }
function tenant(id) { const c=db.prepare('SELECT * FROM clients WHERE id=?').get(id);if(!c)fail('not_found',404);return c; }
function ensureSalon(id) { return db.transaction(()=>{
  const c=tenant(id); if(isModular(id))return salon(id);
  let slug=c.salon.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)||'salon';
  if(db.prepare('SELECT 1 FROM salon_settings WHERE slug=?').get(slug))slug+='-'+id.slice(0,8);
  db.prepare('INSERT INTO salon_settings(client_id,slug,created_at) VALUES(?,?,?)').run(id,slug,nowIso());
  const sid=uid();db.prepare('INSERT INTO staff(id,client_id,name,hours,created_at) VALUES(?,?,?,?,?)').run(sid,id,c.owner||'Salon team',c.hours||db.DEFAULT_HOURS,nowIso());
  for(const s of db.prepare('SELECT id FROM services WHERE client_id=?').all(id))db.prepare('INSERT INTO staff_services VALUES(?,?,?)').run(id,sid,s.id);
  // Unknown legacy assignments conservatively block all qualified staff until reviewed.
  for(const a of db.prepare('SELECT * FROM appointments WHERE client_id=?').all(id)){
    let customer;try{if(a.customer_phone&&a.customer_phone!=='simulator')customer=upsertCustomer(id,{name:a.customer_name,phone:a.customer_phone});}catch{}
    const service=db.prepare('SELECT id FROM services WHERE client_id=? AND name=? COLLATE NOCASE').get(id,a.service_name);
    db.prepare('UPDATE appointments SET service_id=?,customer_id=?,manage_nonce=COALESCE(manage_nonce,?),updated_at=COALESCE(updated_at,created_at) WHERE client_id=? AND id=?').run(service?.id||null,customer?.id||null,uid(),id,a.id);
  }
  const status=['trial','active','payment_failed','cancelled'].includes(c.plan_status)?c.plan_status:'trial';
  db.prepare('INSERT INTO subscriptions(client_id,status,trial_ends_at,updated_at) VALUES(?,?,?,?)').run(id,status,status==='trial'?new Date(Date.now()+14*864e5).toISOString():null,nowIso());
  return salon(id);
}).immediate(); }
function salon(id){const c=tenant(id),s=db.prepare('SELECT * FROM salon_settings WHERE client_id=?').get(id);if(!s)return ensureSalon(id);return{id:c.id,name:c.salon,owner:c.owner,email:c.email,phone:c.phone||'',city:c.city||'',slug:s.slug,description:s.description,address:s.address,hours:JSON.parse(c.hours||db.DEFAULT_HOURS),cancellationHours:s.cancellation_hours,rescheduleHours:s.reschedule_hours,bookingEnabled:!!s.booking_enabled,onboarded:!!s.onboarded,timezone:s.timezone};}
function publicSalon(slug){const s=db.prepare('SELECT client_id FROM salon_settings WHERE slug=?').get(slug);if(!s)fail('not_found',404);const full=salon(s.client_id);if(!full.bookingEnabled)fail('booking_unavailable',404);return {id:full.id,name:full.name,slug:full.slug,phone:full.phone,city:full.city,address:full.address,description:full.description,hours:full.hours,timezone:full.timezone,cancellationHours:full.cancellationHours,rescheduleHours:full.rescheduleHours};}
function updateSalon(id,b){ensureSalon(id);return db.transaction(()=>{const c=salon(id);const hours=b.hours===undefined?c.hours:booking().validateHours(b.hours);if(b.hours!==undefined&&!hours.ok)fail('invalid_hours');
  const slug=b.slug===undefined?c.slug:text(b.slug,70);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))fail('invalid_slug');
  if(db.prepare('SELECT 1 FROM salon_settings WHERE slug=? AND client_id<>?').get(slug,id))fail('slug_in_use',409);
  db.prepare('UPDATE clients SET salon=?,owner=?,phone=?,city=?,hours=? WHERE id=?').run(b.name===undefined?c.name:text(b.name)||fail('name_required'),b.owner===undefined?c.owner:text(b.owner),b.phone===undefined?c.phone:b.phone===''?'':phone(b.phone),b.city===undefined?c.city:text(b.city),JSON.stringify(b.hours===undefined?hours:hours.hours),id);
  const enabled=b.bookingEnabled===undefined?Number(c.bookingEnabled):bool(b.bookingEnabled);
  if(enabled&&!services(id).some(s=>s.active&&s.staffIds.some(x=>staff(id).some(t=>t.id===x&&t.active))))fail('qualified_service_required');
  db.prepare('UPDATE salon_settings SET slug=?,description=?,address=?,cancellation_hours=?,reschedule_hours=?,booking_enabled=?,onboarded=? WHERE client_id=?').run(slug,b.description===undefined?c.description:text(b.description,1000),b.address===undefined?c.address:text(b.address,300),b.cancellationHours===undefined?c.cancellationHours:integer(b.cancellationHours,0,168),b.rescheduleHours===undefined?c.rescheduleHours:integer(b.rescheduleHours,0,168),enabled,b.onboarded===undefined?Number(c.onboarded):bool(b.onboarded),id);return salon(id);
}).immediate();}
function services(id){return db.prepare('SELECT * FROM services WHERE client_id=? ORDER BY category,name').all(id).map(s=>({id:s.id,name:s.name,category:s.category,description:s.description,price:s.price,durationMins:s.duration_mins,depositAmount:s.deposit_amount,active:!!s.active,photoEligible:!!s.photo_eligible,staffIds:db.prepare('SELECT staff_id FROM staff_services WHERE client_id=? AND service_id=?').all(id,s.id).map(x=>x.staff_id)}));}
function staff(id){return db.prepare('SELECT * FROM staff WHERE client_id=? ORDER BY name,id').all(id).map(s=>({id:s.id,name:s.name,email:s.email,phone:s.phone,active:!!s.active,hours:JSON.parse(s.hours),breaks:JSON.parse(s.breaks),serviceIds:db.prepare('SELECT service_id FROM staff_services WHERE client_id=? AND staff_id=?').all(id,s.id).map(x=>x.service_id),timeOff:db.prepare('SELECT id,starts_at AS start,ends_at AS end,reason FROM staff_time_off WHERE client_id=? AND staff_id=? ORDER BY starts_at').all(id,s.id)}));}
function links(id,staffId,serviceIds){if(!Array.isArray(serviceIds)||serviceIds.length>100||new Set(serviceIds).size!==serviceIds.length)fail('invalid_service_ids');for(const sid of serviceIds)if(!db.prepare('SELECT id FROM services WHERE id=? AND client_id=?').get(sid,id))fail('service_not_found',404);db.prepare('DELETE FROM staff_services WHERE client_id=? AND staff_id=?').run(id,staffId);for(const sid of serviceIds)db.prepare('INSERT INTO staff_services VALUES(?,?,?)').run(id,staffId,sid);}
function saveService(id,b,sid){ensureSalon(id);return db.transaction(()=>{const old=sid?services(id).find(s=>s.id===sid):null;if(sid&&!old)fail('not_found',404);const v={name:'',category:'General',description:'',price:0,durationMins:60,depositAmount:0,active:true,...old,...b};
  const name=text(v.name,80)||fail('name_required');if(db.prepare('SELECT id FROM services WHERE client_id=? AND name=? COLLATE NOCASE AND id<>?').get(id,name,sid||''))fail('duplicate_service',409);
  integer(v.price,0,100000);integer(v.durationMins,5,720);integer(v.depositAmount,0,v.price);bool(v.active);const category=text(v.category,80),description=text(v.description,1000);sid=sid||uid();
  db.prepare(`INSERT INTO services(id,client_id,name,price,duration_mins,created_at,category,description,deposit_amount,active) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,price=excluded.price,duration_mins=excluded.duration_mins,category=excluded.category,description=excluded.description,deposit_amount=excluded.deposit_amount,active=excluded.active`).run(sid,id,name,v.price,v.durationMins,nowIso(),category,description,v.depositAmount,Number(v.active));
  if(b.staffIds!==undefined){if(!Array.isArray(b.staffIds)||b.staffIds.length>100||new Set(b.staffIds).size!==b.staffIds.length)fail('invalid_staff_ids');for(const st of b.staffIds)if(!db.prepare('SELECT id FROM staff WHERE client_id=? AND id=?').get(id,st))fail('staff_not_found',404);db.prepare('DELETE FROM staff_services WHERE client_id=? AND service_id=?').run(id,sid);for(const st of b.staffIds)db.prepare('INSERT INTO staff_services VALUES(?,?,?)').run(id,st,sid);}
  return services(id).find(s=>s.id===sid);
}).immediate();}
function saveStaff(id,b,sid){ensureSalon(id);return db.transaction(()=>{const old=sid?staff(id).find(s=>s.id===sid):null;if(sid&&!old)fail('not_found',404);const v={name:'',email:'',phone:'',active:true,hours:salon(id).hours,breaks:[],timeOff:[],serviceIds:[],...old,...b};const name=text(v.name)||fail('name_required'),hours=booking().validateHours(v.hours);if(!hours.ok)fail('invalid_hours');bool(v.active);
  if(!Array.isArray(v.breaks)||v.breaks.length>50)fail('invalid_breaks');const breaks=v.breaks.map(x=>{if(!booking().DAY_KEYS.includes(x.day)||!booking().validTime(x.start)||!booking().validTime(x.end)||x.end<=x.start)fail('invalid_breaks');return{day:x.day,start:x.start,end:x.end};});
  if(!Array.isArray(v.timeOff)||v.timeOff.length>200)fail('invalid_time_off');const timeOff=v.timeOff.map(x=>{const start=Date.parse(x.start),end=Date.parse(x.end);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end-start>366*864e5||!/(Z|[+-]\d\d:\d\d)$/.test(x.start)||!/(Z|[+-]\d\d:\d\d)$/.test(x.end))fail('invalid_time_off');return{id:uid(),start:new Date(start).toISOString(),end:new Date(end).toISOString(),reason:text(x.reason||'',300)};});
  sid=sid||uid();db.prepare(`INSERT INTO staff(id,client_id,name,email,phone,active,hours,breaks,created_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,email=excluded.email,phone=excluded.phone,active=excluded.active,hours=excluded.hours,breaks=excluded.breaks`).run(sid,id,name,email(v.email),v.phone?phone(v.phone):'',Number(v.active),JSON.stringify(hours.hours),JSON.stringify(breaks),nowIso());links(id,sid,v.serviceIds);db.prepare('DELETE FROM staff_time_off WHERE client_id=? AND staff_id=?').run(id,sid);for(const x of timeOff)db.prepare('INSERT INTO staff_time_off VALUES(?,?,?,?,?,?)').run(x.id,id,sid,x.start,x.end,x.reason);return staff(id).find(x=>x.id===sid);
}).immediate();}
function qualifiedStaff(id,serviceId){return db.prepare(`SELECT st.* FROM staff st JOIN staff_services ss ON ss.client_id=st.client_id AND ss.staff_id=st.id JOIN services s ON s.client_id=ss.client_id AND s.id=ss.service_id WHERE st.client_id=? AND s.id=? AND s.active=1 AND st.active=1 ORDER BY st.name,st.id`).all(id,serviceId);}
function checkSlot(id,serviceId,date,time,{staffId,now=new Date(),excludeId}={}){
 const b=booking(),s=db.prepare('SELECT * FROM services WHERE client_id=? AND id=? AND active=1').get(id,serviceId);if(!s)return{ok:false,reason:'unknown_service'};
 if(!b.validDuration(s.duration_mins))return{ok:false,reason:'invalid_duration'};if(!Number.isInteger(s.price)||s.price<0||s.price>100000||!Number.isInteger(s.deposit_amount)||s.deposit_amount<0||s.deposit_amount>s.price)return{ok:false,reason:'invalid_service'};
 if(!b.validDate(date)||!b.validTime(time))return{ok:false,reason:'bad_datetime'};const start=Date.parse(`${date}T${time}:00+02:00`),end=start+s.duration_mins*6e4;
 if(!Number.isFinite(new Date(now).getTime())||start<=new Date(now).getTime())return{ok:false,reason:'past_datetime'};if(start>new Date(now).getTime()+366*864e5)return{ok:false,reason:'booking_horizon'};
 const c=tenant(id),range=b.hoursForDate(b.parseHours(c),date);if(!range)return{ok:false,reason:'closed'};if(time<range.open||end>Date.parse(`${date}T${range.close}:00+02:00`))return{ok:false,reason:'outside_hours'};
 let candidates=qualifiedStaff(id,serviceId);if(staffId&&staffId!=='any')candidates=candidates.filter(x=>x.id===staffId);if(!candidates.length)return{ok:false,reason:'no_qualified_staff'};
 const all=db.prepare("SELECT * FROM appointments WHERE client_id=? AND status IN ('confirmed','pending') AND id<>?").all(id,excludeId||'');
 for(const st of candidates){const r=b.hoursForDate(b.parseHours(st),date);if(!r||time<r.open||end>Date.parse(`${date}T${r.close}:00+02:00`))continue;const day=b.DAY_KEYS[new Date(`${date}T00:00:00Z`).getUTCDay()];
 if(JSON.parse(st.breaks).some(x=>x.day===day&&start<Date.parse(`${date}T${x.end}:00+02:00`)&&end>Date.parse(`${date}T${x.start}:00+02:00`)))continue;
 if(db.prepare('SELECT starts_at,ends_at FROM staff_time_off WHERE client_id=? AND staff_id=?').all(id,st.id).some(x=>start<Date.parse(x.ends_at)&&end>Date.parse(x.starts_at)))continue;
 if(all.some(a=>{if(a.staff_id&&a.staff_id!==st.id)return false;const t=b.storedInstant(a.starts_at);return !Number.isFinite(t)||!b.validDuration(a.duration_mins)||start<t+a.duration_mins*6e4&&end>t;}))continue;
 return{ok:true,staff:{id:st.id,name:st.name}};
 }return{ok:false,reason:'slot_taken'};
}
function availableSlots(id,serviceId,date,options={}){if(!booking().validDate(date))return[];const range=booking().hoursForDate(booking().parseHours(tenant(id)),date);if(!range)return[];const mins=x=>Number(x.slice(0,2))*60+Number(x.slice(3));const out=[];for(let m=mins(range.open);m<mins(range.close);m+=15){const time=String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');const c=checkSlot(id,serviceId,date,time,options);if(c.ok)out.push({time,staffId:c.staff.id,staffName:c.staff.name});}return out;}
function upsertCustomer(id,b,{preserveExisting=false}={}){const n=phone(b.phone),name=text(b.name)||fail('name_required'),e=email(b.email);const c=db.prepare('SELECT * FROM customers WHERE client_id=? AND phone=?').get(id,n),at=nowIso();if(c){if(preserveExisting)return c;db.prepare('UPDATE customers SET name=?,email=?,updated_at=? WHERE client_id=? AND id=?').run(name,e||c.email,at,id,c.id);if(b.whatsappOptIn!==undefined)setOptIn(id,c.id,b.whatsappOptIn);return db.prepare('SELECT * FROM customers WHERE id=? AND client_id=?').get(c.id,id);}const cid=uid();db.prepare('INSERT INTO customers(id,client_id,name,phone,email,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(cid,id,name,n,e,at,at);if(b.whatsappOptIn!==undefined)setOptIn(id,cid,b.whatsappOptIn);return db.prepare('SELECT * FROM customers WHERE client_id=? AND id=?').get(id,cid);}
function setOptIn(id,cid,value){bool(value);db.prepare('UPDATE customers SET whatsapp_opt_in=?,opt_in_at=CASE WHEN ?=1 THEN ? ELSE opt_in_at END,opt_out_at=CASE WHEN ?=0 THEN ? ELSE NULL END WHERE client_id=? AND id=?').run(Number(value),Number(value),nowIso(),Number(value),nowIso(),id,cid);}
function appointment(id,aid){const a=db.prepare(`SELECT a.*,s.name AS staff_name FROM appointments a LEFT JOIN staff s ON s.client_id=a.client_id AND s.id=a.staff_id WHERE a.client_id=? AND a.id=?`).get(id,aid);if(!a)fail('not_found',404);const paid=db.prepare("SELECT COALESCE(SUM(CASE WHEN kind='refund' THEN -amount ELSE amount END),0) AS n FROM payments WHERE client_id=? AND appointment_id=?").get(id,aid).n;return{id:a.id,customerId:a.customer_id,customerName:a.customer_name,customerPhone:a.customer_phone,customerEmail:a.customer_email||'',serviceId:a.service_id,serviceName:a.service_name,staffId:a.staff_id,staffName:a.staff_name||'Assignment needs review',startsAt:a.starts_at,durationMins:a.duration_mins,status:a.status,price:a.price_at_booking,depositAmount:a.deposit_amount,paidAmount:paid,source:a.source,version:a.version,quoteKind:a.quote_kind};}
function emit(id,aid,kind){const a=appointment(id,aid),eid=uid(),at=nowIso();const inserted=db.prepare('INSERT OR IGNORE INTO appointment_events VALUES(?,?,?,?,?,?,?)').run(eid,id,aid,a.version,kind,JSON.stringify(a),at);if(!inserted.changes)return;
 db.prepare("UPDATE notification_outbox SET status='superseded',reason='appointment_changed' WHERE client_id=? AND appointment_id=? AND status IN ('queued','blocked')").run(id,aid);
 const body=`BEAUTYDESK · SMARTER SALON MANAGEMENT\n${tenant(id).salon}: ${a.serviceName} with ${a.staffName}, ${a.startsAt}, R${a.price??'not recorded'}. Deposit required: R${a.depositAmount}. Status: ${a.status}.`;
 db.prepare('INSERT INTO notification_outbox(id,client_id,appointment_id,event_id,kind,due_at,body,created_at) VALUES(?,?,?,?,?,?,?,?)').run(uid(),id,aid,eid,kind,at,body,at);
 if(['confirmed','pending'].includes(a.status)){const due=new Date(booking().storedInstant(a.startsAt)-24*36e5).toISOString();if(due>at)db.prepare('INSERT INTO notification_outbox(id,client_id,appointment_id,event_id,kind,due_at,body,created_at) VALUES(?,?,?,?,?,?,?,?)').run(uid(),id,aid,eid,'reminder',due,'Reminder: '+body,at);}
}
function recordLegacyAppointment(aid,staffId){const a=db.prepare('SELECT * FROM appointments WHERE id=?').get(aid);if(!a||!isModular(a.client_id))return;const s=db.prepare('SELECT * FROM services WHERE client_id=? AND name=? COLLATE NOCASE').get(a.client_id,a.service_name);if(!s)return;const c=upsertCustomer(a.client_id,{name:a.customer_name,phone:a.customer_phone});db.prepare('UPDATE appointments SET service_id=?,staff_id=?,customer_id=?,deposit_amount=?,manage_nonce=COALESCE(manage_nonce,?),updated_at=? WHERE id=? AND client_id=?').run(s.id,staffId||a.staff_id||null,c.id,s.deposit_amount,uid(),nowIso(),aid,a.client_id);emit(a.client_id,aid,'confirmed');}
function createAppointment(id,b,{now=new Date()}={}){ensureSalon(id);return db.transaction(()=>{if(b.confirmed!==true)fail('explicit_confirmation_required');const ik=key(b.idempotencyKey),fp=fingerprint(b),prior=db.prepare('SELECT * FROM booking_requests WHERE client_id=? AND idempotency_key=?').get(id,ik);if(prior){if(prior.fingerprint!==fp)fail('idempotency_conflict',409);return appointment(id,prior.appointment_id);}
 const s=db.prepare('SELECT * FROM services WHERE client_id=? AND id=? AND active=1').get(id,b.serviceId);if(!s)fail('unknown_service',404);if(b.expectedName!==undefined&&b.expectedName!==s.name)fail('service_changed',409);if(b.expectedPrice!==undefined&&(b.expectedPrice!==s.price||b.expectedDuration!==s.duration_mins||b.expectedDeposit!==s.deposit_amount))fail('service_changed',409);
 const slot=checkSlot(id,s.id,b.date,b.time,{staffId:b.staffId,now});if(!slot.ok)fail(slot.reason,409);if(b.expectedStaffName!==undefined&&b.expectedStaffName!==slot.staff.name)fail('staff_changed',409);const c=upsertCustomer(id,{name:b.customerName,phone:b.customerPhone,email:b.customerEmail,whatsappOptIn:b.whatsappOptIn},{preserveExisting:b.source==='public'});const aid=uid(),at=nowIso();
 db.prepare(`INSERT INTO appointments(id,client_id,customer_name,customer_phone,service_name,starts_at,duration_mins,status,source,created_at,price_at_booking,service_id,staff_id,customer_id,deposit_amount,manage_nonce,updated_at,customer_email) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(aid,id,text(b.customerName)||fail('name_required'),c.phone,s.name,`${b.date}T${b.time}:00+02:00`,s.duration_mins,'confirmed',b.source==='public'?'public':'manual',at,s.price,s.id,slot.staff.id,c.id,s.deposit_amount,uid(),at,email(b.customerEmail));
 db.prepare('INSERT INTO booking_requests VALUES(?,?,?,?)').run(id,ik,fp,aid);emit(id,aid,'confirmed');return appointment(id,aid);
}).immediate();}
function manageToken(id,aid){const a=db.prepare('SELECT manage_nonce FROM appointments WHERE client_id=? AND id=?').get(id,aid);if(!a?.manage_nonce)fail('management_unavailable',409);const sig=crypto.createHmac('sha256',process.env.JWT_SECRET).update(`${id}:${aid}:${a.manage_nonce}`).digest('base64url');return aid+'.'+sig;}
function fromToken(token){if(typeof token!=='string'||token.length>150)fail('not_found',404);const aid=token.split('.')[0],a=db.prepare('SELECT client_id FROM appointments WHERE id=?').get(aid);if(!a)fail('not_found',404);const expected=manageToken(a.client_id,aid),x=Buffer.from(expected),y=Buffer.from(token);if(x.length!==y.length||!crypto.timingSafeEqual(x,y))fail('not_found',404);return{clientId:a.client_id,booking:appointment(a.client_id,aid)};}
function changeAppointment(id,aid,b,{publicRequest=false,now=new Date()}={}){return db.transaction(()=>{const a=appointment(id,aid);if(b.status==='cancelled'&&a.status==='cancelled')return a;const rescheduling=b.date!==undefined||b.time!==undefined||b.staffId!==undefined;if(b.version!==a.version){const sameSchedule=rescheduling&&b.date&&b.time&&`${b.date}T${b.time}:00+02:00`===a.startsAt&&(!b.staffId||b.staffId===a.staffId)&&!b.status;const sameStatus=!rescheduling&&b.status===a.status;if(sameSchedule||sameStatus)return a;fail('appointment_changed',409);}if(['completed','cancelled','no-show'].includes(a.status))fail('terminal_appointment',409);
 if(publicRequest){if(!rescheduling&&b.status!=='cancelled')fail('forbidden',403);const s=salon(id),hours=rescheduling?s.rescheduleHours:s.cancellationHours;if(booking().storedInstant(a.startsAt)-new Date(now).getTime()<hours*36e5)fail('change_window_closed',409);}
 let starts=a.startsAt,st=a.staffId,kind='status_changed';if(rescheduling){if(b.status&&b.status!==a.status)fail('one_change_at_a_time');const date=b.date,time=b.time,slot=checkSlot(id,a.serviceId,date,time,{staffId:b.staffId||a.staffId,now,excludeId:aid});if(!slot.ok)fail(slot.reason,409);const currentService=db.prepare('SELECT duration_mins FROM services WHERE client_id=? AND id=?').get(id,a.serviceId);if(currentService.duration_mins!==a.durationMins)fail('service_changed',409);starts=`${date}T${time}:00+02:00`;st=slot.staff.id;kind='rescheduled';if(starts===a.startsAt&&st===a.staffId)return a;}
 const status=b.status||a.status;if(!['confirmed','pending','completed','cancelled','no-show'].includes(status))fail('invalid_status');if(!rescheduling&&status===a.status)return a;if(['completed','no-show'].includes(status)&&booking().storedInstant(a.startsAt)>new Date(now).getTime())fail('appointment_not_started',409);
 db.prepare('UPDATE appointments SET starts_at=?,staff_id=?,status=?,version=version+1,updated_at=? WHERE client_id=? AND id=?').run(starts,st,status,nowIso(),id,aid);emit(id,aid,status==='cancelled'?'cancelled':kind);return appointment(id,aid);
}).immediate();}
function createQuote(id,b){ensureSalon(id);db.prepare('DELETE FROM booking_quotes WHERE expires_at<? AND appointment_id IS NULL').run(nowIso());db.prepare('DELETE FROM booking_quotes WHERE created_at<? AND appointment_id IS NOT NULL').run(new Date(Date.now()-864e5).toISOString());const s=db.prepare('SELECT * FROM services WHERE client_id=? AND id=? AND active=1').get(id,b.serviceId);if(!s)fail('unknown_service',404);const slot=checkSlot(id,s.id,b.date,b.time,{staffId:b.staffId});if(!slot.ok)fail(slot.reason,409);const p={serviceId:s.id,staffId:slot.staff.id,date:b.date,time:b.time,customerName:text(b.customerName)||fail('name_required'),customerPhone:phone(b.customerPhone),customerEmail:email(b.customerEmail),whatsappOptIn:b.whatsappOptIn===undefined?false:!!bool(b.whatsappOptIn),expectedName:s.name,expectedStaffName:slot.staff.name,expectedPrice:s.price,expectedDuration:s.duration_mins,expectedDeposit:s.deposit_amount,source:'public'};const qid=uid(),expiresAt=new Date(Date.now()+15*6e4).toISOString();db.prepare('INSERT INTO booking_quotes VALUES(?,?,?,?,?,NULL)').run(qid,id,JSON.stringify(p),nowIso(),expiresAt);return{quoteId:qid,expiresAt,summary:{serviceName:s.name,staffName:slot.staff.name,date:p.date,time:p.time,price:s.price,depositAmount:s.deposit_amount,durationMins:s.duration_mins,customerName:p.customerName,customerPhone:p.customerPhone,customerEmail:p.customerEmail}};}
function confirmQuote(id,b){return db.transaction(()=>{if(b.confirmed!==true)fail('explicit_confirmation_required');key(b.idempotencyKey);const q=db.prepare('SELECT * FROM booking_quotes WHERE client_id=? AND id=?').get(id,b.quoteId);if(!q)fail('not_found',404);if(q.appointment_id)return{booking:appointment(id,q.appointment_id),manageToken:manageToken(id,q.appointment_id)};if(q.expires_at<=nowIso())fail('quote_expired',409);const a=createAppointment(id,{...JSON.parse(q.payload),confirmed:true,idempotencyKey:b.idempotencyKey});db.prepare('UPDATE booking_quotes SET appointment_id=? WHERE id=? AND client_id=?').run(a.id,q.id,id);return{booking:a,manageToken:manageToken(id,a.id)};}).immediate();}
function recordPayment(id,b){return db.transaction(()=>{const ik=key(b.idempotencyKey),fp=fingerprint(b),old=db.prepare('SELECT * FROM payments WHERE client_id=? AND idempotency_key=?').get(id,ik);if(old){if(old.fingerprint!==fp)fail('idempotency_conflict',409);return old;}const a=appointment(id,b.appointmentId);integer(b.amount,1,1000000);if(!['deposit','payment','refund'].includes(b.kind)||!['cash','bank_transfer','card_external'].includes(b.method))fail('invalid_payment');if(b.kind==='refund'&&b.amount>a.paidAmount)fail('refund_exceeds_payments',409);if(b.kind!=='refund'&&(a.price==null||a.paidAmount+b.amount>a.price))fail('payment_exceeds_booking_value',409);const pid=uid();db.prepare('INSERT INTO payments VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(pid,id,a.id,a.customerId,b.amount,b.kind,b.method,text(b.reference||'',200),ik,fp,nowIso());return db.prepare('SELECT * FROM payments WHERE id=? AND client_id=?').get(pid,id);}).immediate();}
function processMockNotifications(now=new Date()){return db.transaction(()=>{const rows=db.prepare("SELECT * FROM notification_outbox WHERE status='queued' AND due_at<=? ORDER BY due_at LIMIT 100").all(new Date(now).toISOString());for(const r of rows){const a=db.prepare('SELECT customer_id,status FROM appointments WHERE client_id=? AND id=?').get(r.client_id,r.appointment_id),c=a&&db.prepare('SELECT whatsapp_opt_in FROM customers WHERE client_id=? AND id=?').get(r.client_id,a.customer_id);const reason=!c?.whatsapp_opt_in?'opt_in_required':r.kind==='reminder'&&!['confirmed','pending'].includes(a.status)?'appointment_inactive':'live_provider_disabled';db.prepare("UPDATE notification_outbox SET status=?,reason=?,processed_at=? WHERE id=? AND status='queued'").run(reason==='live_provider_disabled'?'mock_ready':'blocked',reason,nowIso(),r.id);}return rows.length;}).immediate();}
module.exports={db,fail,text,integer,phone,email,key,isModular,ensureSalon,salon,publicSalon,updateSalon,services,staff,saveService,saveStaff,qualifiedStaff,checkSlot,availableSlots,upsertCustomer,setOptIn,appointment,emit,recordLegacyAppointment,createAppointment,manageToken,fromToken,changeAppointment,createQuote,confirmQuote,recordPayment,processMockNotifications};
module.exports.depositAmount = (clientId, serviceId) => db.prepare('SELECT deposit_amount FROM services WHERE client_id=? AND id=?').get(clientId,serviceId)?.deposit_amount || 0;
