const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),test=require('node:test'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8'),js=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length,'unique HTML IDs');
const nodes=new Map();
function node(id){ if(!nodes.has(id))nodes.set(id,{id,value:'',innerHTML:'',textContent:'',hidden:false,disabled:false,checked:false,style:{},attrs:{},dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},setAttribute(k,v){this.attrs[k]=v},querySelectorAll(){return []},querySelector(){return node('stub-input')},focus(){},reset(){this.resets=(this.resets||0)+1},scrollHeight:0,scrollTop:0});return nodes.get(id); }
ids.forEach(node); ['mon','tue','wed','thu','fri','sat','sun'].forEach(d=>node('hours_'+d));
let calls=[], handler=async()=>({ok:true}),confirm=true;
const context={console,TextEncoder,Date,Set,Array,Object,Number,String,Math,JSON,Error,Promise,encodeURIComponent,location:{hash:'',pathname:'/',search:''},history:{pushState(){}},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},window:{scrollTo(){},addEventListener(){},confirm:()=>confirm},document:{hidden:false,activeElement:null,getElementById:node,querySelectorAll:()=>[],addEventListener(){}},fetch:async(url,options)=>{calls.push({url,...options});let data=await handler(url,options);return {ok:!data.error,status:data.status||200,json:async()=>data};}};
vm.createContext(context);vm.runInContext(js,context);
const run=code=>vm.runInContext(code,context);
function setClient(){run(`CURRENT_CLIENT={id:'fixture',salon:'Fixture salon',whatsapp_enabled:true,greeting:'Saved greeting',hours:JSON.stringify({mon:'09:00-18:00',tue:'closed',wed:'closed',thu:'closed',fri:'closed',sat:'closed',sun:'closed'}),responder_mode:'guided',wa_signature_configured:false,wa_connected:false}; CURRENT_SERVICES=[]; ACTIVE_VIEW='client';`)}
const form={elements:{namedItem:name=>({value:({salon:'Fixture',owner:'Fixture',email:'fixture@example.test',phone:'123',city:'Test',name:'Fixture',message:'hello'})[name]})},querySelectorAll:()=>[node('form-button')],reset(){this.resets=(this.resets||0)+1}};
test('frontend pilot flows: validation, duplicate requests, honest status and safe rendering', async()=>{
 let passed=0;const done=name=>{passed++;console.log('PASS',name)};
 for(const value of ['closed','00:00-23:59','09:00-18:00'])assert.equal(run(`validHoursValue(${JSON.stringify(value)})`),true);
 for(const value of ['',null,'9:00-18:00','24:00-25:00','18:00-09:00','09:00-09:00','09:60-18:00'])assert.equal(run(`validHoursValue(${JSON.stringify(value)})`),false);done('hours format and ordering');
 setClient();calls=[];['mon','tue','wed','thu','fri','sat','sun'].forEach(d=>node('hours_'+d).value='closed');node('hours_mon').value='18:00-09:00';await context.saveHours();assert.equal(calls.length,0);assert.match(node('hoursError').textContent,/Monday/);node('hours_mon').value='09:00-18:00';node('waGreeting').value='Unsaved greeting';node('waToggle').checked=false;await context.saveHours();assert.equal(calls.length,1);assert.equal(JSON.parse(calls[0].body).greeting,undefined);assert.equal(JSON.parse(calls[0].body).whatsappEnabled,undefined);done('invalid hours blocked and unrelated drafts preserved');
 calls=[];let release;handler=async(url,opt)=>opt.method==='POST'?new Promise(resolve=>{release=resolve}):[];node('svcName').value='Fixture service';node('svcPrice').value='350';node('svcDuration').value='45';const adding=context.addService();await context.addService();assert.equal(calls.filter(c=>c.method==='POST').length,1);assert.equal(node('addServiceButton').disabled,true);release({ok:true});await adding;assert.equal(node('addServiceButton').disabled,false);assert.equal(node('svcName').value,'');done('duplicate service clicks submit once and restore controls');
 calls=[];handler=async()=>new Promise(resolve=>{release=resolve});const event={target:form,preventDefault(){}};const signup=context.submitSignup(event);await context.submitSignup(event);assert.equal(calls.length,1);release({ok:true});await signup;assert.equal(form.resets,1);done('duplicate signup submissions send once');
 handler=async()=>({error:'invalid_credentials',status:401});node('clientEmail').value='fixture@example.test';node('clientPassword').value='fake-test-password';await context.clientLogin(event);assert.match(node('toast').textContent,/not recognised/);done('invalid login reports credential problem');
 for(const status of [401,429,500]){handler=async()=>({error:'internal_diagnostic_not_for_display',status});await context.clientLogin(event);assert.match(node('toast').textContent,status===401?/not recognised/:status===429?/Too many attempts/:/could not complete sign-in/);assert.doesNotMatch(node('toast').textContent,/internal_diagnostic/);assert.equal(node('form-button').disabled,false);}handler=async()=>{throw new Error('offline')};await context.clientLogin(event);assert.match(node('toast').textContent,/Check your connection/);assert.equal(node('form-button').disabled,false);done('login distinguishes generic credentials, throttling, server and network failures');
 setClient();calls=[];node('simInput').value='test';handler=async(url,opt)=>opt.method==='POST'?new Promise(resolve=>{release=resolve}):[];const sending=context.sendSimMessage();await context.sendSimMessage();await context.resetSimulator();assert.equal(calls.length,1);release({reply:'test reply',mode:'rules_fallback'});await sending;assert.match(node('simModePill').textContent,/fallback/);assert.equal(node('simSendButton').disabled,false);done('simulator duplicate send and overlapping reset blocked');
 context.renderAppointments([{id:'test',source:'simulator',starts_at:'2026-10-02T12:00:00+02:00'},{id:'legacy-whatsapp',source:'whatsapp_ai',customer_phone:'whatsapp-ai',starts_at:'2026-10-02T13:00:00+02:00'},{id:'real',source:'whatsapp',starts_at:'2026-10-02T10:00:00Z',customer_name:'<script>bad</script>',service_name:'Cut',duration_mins:45}]);assert.equal(node('clientBookingCount').textContent,'3');assert.equal((node('apptList').innerHTML.match(/Legacy booking · verify with customer/g)||[]).length,2);assert.match(node('apptList').innerHTML,/Keep its slot blocked/);assert.match(node('apptList').innerHTML,/12:00 SAST/);assert.ok(!node('apptList').innerHTML.includes('<script>'));done('legacy bookings retained with verification warnings, South Africa timezone and escaping');
 context.renderRecentMessages([{customer_phone:'simulator',body:'simulation',created_at:new Date().toISOString()},{customer_name:'Fixture',customer_phone:'test',body:'<img src=x>',created_at:new Date().toISOString()}]);assert.ok(!node('msgList').innerHTML.includes('simulation'));assert.ok(!node('msgList').innerHTML.includes('<img'));done('simulator messages excluded and text escaped');
 context.renderClientStatus({responder_mode:'guided',wa_signature_configured:false});assert.equal(node('responderMode').textContent,'Guided booking');assert.match(node('waSignatureStatus').textContent,/Blocked/);context.renderClientStatus({responder_mode:'claude',wa_signature_configured:true});assert.match(node('responderModeNote').textContent,/unverified/);done('actual mode and webhook signature blockers displayed');
 calls=[];handler=async()=>({ok:true});node('currentPassword').value='fixture-old-password';node('newPassword').value='fixture-new-password';node('confirmPassword').value='mismatch';await context.changeClientPassword(event);assert.equal(calls.length,0);node('confirmPassword').value='fixture-new-password';await context.changeClientPassword(event);assert.equal(calls[0].url,'/api/client/password');assert.equal(JSON.parse(calls[0].body).newPassword,'fixture-new-password');node('newPassword').value='😀'.repeat(20);node('confirmPassword').value=node('newPassword').value;calls=[];await context.changeClientPassword(event);assert.equal(calls.length,0);done('password mismatch and byte bounds blocked; correct payload');
 calls=[];confirm=false;await context.cancelAppointment('real',node('cancel'));assert.equal(calls.length,0);await context.acknowledgeWhatsappReview('review',node('review'));assert.equal(calls.length,0);done('cancel and review dismissal make no mutation');
 context.renderWhatsappReviews([{id:'review',customer_name:'Fixture',incoming_body:'<script>injected</script>',reply_body:'text',state:'unknown',appointment_id:'saved',appointment_service:'<script>service</script>',appointment_starts_at:'2027-01-05T12:00:00+02:00',appointment_status:'confirmed',created_at:new Date().toISOString()}]);assert.ok(!node('waReviewList').innerHTML.includes('<script>'));assert.match(node('waReviewList').innerHTML,/Mark reviewed/);assert.match(node('waReviewList').innerHTML,/Appointment already saved/);assert.match(node('waReviewList').innerHTML,/marking reviewed does not cancel/);done('manual review queue escapes messages and preserves saved-booking warning');
 calls=[];setClient();const releases=[];handler=async()=>new Promise(resolve=>releases.push(resolve));node('apptList').innerHTML='Newer panel';const refreshing=context.refreshClientData(false);run('clientGeneration++;');releases.forEach((resolve,i)=>resolve(i===0?{id:'stale',responder_mode:'claude'}:[]));await refreshing;assert.equal(node('apptList').innerHTML,'Newer panel');assert.equal(run('CURRENT_CLIENT.id'),'fixture');done('late refresh cannot overwrite newer navigation');
 calls=[];handler=async()=>({ok:true});await context.api('POST','/api/client/logout');await context.api('DELETE','/api/client/services/fixture');assert.equal(calls[0].body,'{}');assert.equal(calls[1].body,'{}');assert.equal(calls[0].headers['Content-Type'],'application/json');done('bodyless mutations use required JSON contract');
 assert.ok(!html.includes('240+'));assert.ok(!html.includes('next billing 1 Oct'));assert.ok(!html.includes('Cut our missed calls'));assert.match(html,/PayFast is not integrated/);assert.match(html,/no real appointments are created/);done('unverified marketing and payment claims removed');
 console.log(`${passed} frontend checks passed`);
 assert.equal(passed,16);
});

test('photo toggle enforces host/catalog gates, preserves failed drafts and prevents duplicate saves',async()=>{
 setClient();calls=[];run('PHOTO_SETTINGS_DIRTY=false');context.renderPhotoSettings(run('CURRENT_CLIENT'));
 assert.equal(node('photoEstimatesToggle').disabled,true);assert.match(node('photoEstimatesPill').textContent,/Host setup/);
 node('photoEstimatesToggle').checked=true;await context.savePhotoSettings();assert.equal(calls.length,0);
 run('CURRENT_CLIENT.photo_estimates_status={ready:true};');context.renderPhotoSettings(run('CURRENT_CLIENT'));
 assert.match(node('photoEstimatesPill').textContent,/No eligible/);node('photoEstimatesToggle').checked=true;await context.savePhotoSettings();assert.equal(calls.length,0);
 run(`CURRENT_SERVICES=[{id:'photo-test',photo_eligible:1,photo_category:'nails',photo_description:'Single colour only; no removal.'}];`);
 context.renderPhotoSettings(run('CURRENT_CLIENT'));assert.equal(node('photoEstimatesToggle').disabled,false);
 node('photoEstimatesToggle').checked=true;context.togglePhotoEstimates();assert.match(node('photoEstimatesStatus').textContent,/Unsaved change/);
 handler=async()=>({error:'photo_host_not_ready',status:409});await context.savePhotoSettings();assert.equal(run('PHOTO_SETTINGS_DIRTY'),true);assert.equal(node('photoEstimatesToggle').checked,true);assert.match(node('photoSettingsFeedback').textContent,/not ready/);
 calls=[];let release;handler=async()=>new Promise(r=>release=r);const pending=context.savePhotoSettings();await context.savePhotoSettings();assert.equal(calls.length,1);assert.equal(node('photoEstimatesToggle').disabled,true);assert.deepEqual(JSON.parse(calls[0].body),{photoEstimatesEnabled:true});
 release({ok:true});await pending;assert.equal(run('PHOTO_SETTINGS_DIRTY'),false);assert.equal(run('CURRENT_CLIENT.photo_estimates_enabled'),true);assert.match(node('photoEstimatesPill').textContent,/unverified/);
 run('CURRENT_CLIENT.photo_estimates_status={ready:false}');context.renderPhotoSettings(run('CURRENT_CLIENT'));assert.equal(node('photoEstimatesToggle').disabled,false);node('photoEstimatesToggle').checked=false;context.togglePhotoEstimates();handler=async()=>({ok:true});await context.savePhotoSettings();assert.equal(run('CURRENT_CLIENT.photo_estimates_enabled'),false);
});

 test('owner appointment list labels photo prices as estimates and escapes customer content',()=>{
 context.renderAppointments([{id:'photo',customer_name:'<img src=x>',service_name:'Gel nails',customer_phone:'27820000000',starts_at:'2026-10-03T10:00:00+02:00',duration_mins:60,source:'whatsapp',quote_kind:'photo_menu_estimate',price_at_booking:250}]);
 assert.match(node('apptList').innerHTML,/Photo menu estimate: R250/);assert.match(node('apptList').innerHTML,/agree any price change/);assert.doesNotMatch(node('apptList').innerHTML,/<img/);
 });
