const {test}=require('node:test');const assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),{spawn}=require('child_process');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bd-domain-'));process.env.DB_PATH=path.join(dir,'fixture.db');process.env.JWT_SECRET='fixture-only-modular-jwt-32-characters';const d=require('../modules/salon'),db=d.db;const now=new Date(),stamp=now.toISOString();const nextMonday=new Date(Date.now()+7*864e5);while(nextMonday.getUTCDay()!==1)nextMonday.setUTCDate(nextMonday.getUTCDate()+1);const date=nextMonday.toISOString().slice(0,10),nextDate=new Date(nextMonday.getTime()+864e5).toISOString().slice(0,10);let count=0;
function fixture(){const id='salon-'+ ++count;db.prepare('INSERT INTO clients(id,salon,owner,email,password_hash,hours,created_at) VALUES(?,?,?,?,?,?,?)').run(id,'Salon '+count,'Owner '+count,'fixture'+count+'@example.invalid','fake-only',db.DEFAULT_HOURS,stamp);d.ensureSalon(id);const a=d.staff(id)[0],s=d.saveService(id,{name:'Manicure',price:300,durationMins:60,depositAmount:50,staffIds:[a.id]});return{id,a,s};}
function request(f,patch={}){return{serviceId:f.s.id,staffId:f.a.id,date:date,time:'10:00',customerName:'Mpho Fixture',customerPhone:'+27820000000',confirmed:true,idempotencyKey:'request_'+ ++count,...patch};}
function throws(fn,code){assert.throws(fn,e=>e.message===code);}

test('additive migration runs once and leaves legacy records intact',()=>{const f=fixture();require('../modules/migrations')(db);assert.equal(db.prepare('SELECT count(*) n FROM schema_migrations').get().n,2);assert.equal(db.prepare('SELECT password_hash FROM clients WHERE id=?').get(f.id).password_hash,'fake-only');});
test('tenant relationships reject foreign service/staff IDs and mutations',()=>{const f=fixture(),g=fixture();throws(()=>d.saveStaff(f.id,{serviceIds:[g.s.id]},f.a.id),'service_not_found');throws(()=>d.saveService(f.id,{staffIds:[g.a.id]},f.s.id),'staff_not_found');throws(()=>d.saveStaff(f.id,{name:'Stolen'},g.a.id),'not_found');throws(()=>d.saveService(f.id,{name:'Stolen'},g.s.id),'not_found');assert.equal(d.staff(g.id)[0].name,g.a.name);});
test('availability respects service duration, salon/staff hours, breaks, time off and qualification',()=>{const f=fixture();d.saveStaff(f.id,{hours:{...d.salon(f.id).hours,mon:'10:00-16:00'},breaks:[{day:'mon',start:'12:00',end:'13:00'}],timeOff:[{start:date+'T14:00:00+02:00',end:date+'T15:00:00+02:00',reason:'Appointment'}]},f.a.id);const slots=d.availableSlots(f.id,f.s.id,date,{now});assert(slots.some(x=>x.time==='10:00'));for(const time of ['09:00','11:15','12:00','13:15','14:00','15:15'])assert(!slots.some(x=>x.time===time),time);assert(slots.some(x=>x.time==='13:00'));assert(slots.some(x=>x.time==='15:00'));assert.equal(d.checkSlot(f.id,f.s.id,date,'10:00',{staffId:'foreign',now}).reason,'no_qualified_staff');});
test('explicit confirmation, phone normalization and transactionally idempotent booking',()=>{const f=fixture(),b=request(f,{whatsappOptIn:true});throws(()=>d.createAppointment(f.id,{...b,confirmed:false},{now}),'explicit_confirmation_required');const a=d.createAppointment(f.id,b,{now}),again=d.createAppointment(f.id,b,{now});assert.equal(a.id,again.id);assert.equal(a.customerPhone,'27820000000');assert.equal(a.staffId,f.a.id);assert.equal(a.depositAmount,50);assert.equal(db.prepare('SELECT count(*) n FROM appointment_events WHERE appointment_id=?').get(a.id).n,1);throws(()=>d.createAppointment(f.id,{...b,time:'11:00'},{now}),'idempotency_conflict');throws(()=>d.createAppointment(f.id,request(f),{now}),'slot_taken');});
test('any staff uses qualified free capacity, never unrelated free technician',()=>{const f=fixture(),b=d.saveStaff(f.id,{name:'Second',serviceIds:[f.s.id]}),unqualified=d.saveStaff(f.id,{name:'Unqualified'});const first=d.createAppointment(f.id,request(f),{now}),second=d.createAppointment(f.id,request(f,{staffId:'any',customerPhone:'27820000001'}),{now});assert.equal(first.staffId,f.a.id);assert.equal(second.staffId,b.id);assert.notEqual(second.staffId,unqualified.id);throws(()=>d.createAppointment(f.id,request(f,{staffId:'any'}),{now}),'slot_taken');});
test('null-staff legacy appointments conservatively block all qualified staff',()=>{const f=fixture();db.prepare('INSERT INTO appointments(id,client_id,customer_name,service_name,starts_at,duration_mins,created_at) VALUES(?,?,?,?,?,?,?)').run('legacy'+count,f.id,'Legacy','Manicure',date+'T10:00:00',60,stamp);d.saveStaff(f.id,{name:'Other',serviceIds:[f.s.id]});assert.equal(d.checkSlot(f.id,f.s.id,date,'10:00',{now}).reason,'slot_taken');});
test('reschedule atomically releases old capacity, increments version, supersedes reminder and rejects stale mutation',()=>{const f=fixture(),a=d.createAppointment(f.id,request(f),{now});const r=d.changeAppointment(f.id,a.id,{date:date,time:'11:00',version:a.version},{now});assert.equal(r.version,2);assert.equal(d.checkSlot(f.id,f.s.id,date,'10:00',{now}).ok,true);assert.equal(d.checkSlot(f.id,f.s.id,date,'11:00',{now}).ok,false);throws(()=>d.changeAppointment(f.id,a.id,{status:'pending',version:1},{now}),'appointment_changed');assert(db.prepare("SELECT count(*) n FROM notification_outbox WHERE appointment_id=? AND status='superseded'").get(a.id).n>0);});
test('pending consumes capacity, cancelled frees it; repeat cancel emits no duplicate',()=>{const f=fixture(),a=d.createAppointment(f.id,request(f),{now}),p=d.changeAppointment(f.id,a.id,{status:'pending',version:1},{now});assert.equal(d.checkSlot(f.id,f.s.id,date,'10:00',{now}).ok,false);const c=d.changeAppointment(f.id,a.id,{status:'cancelled',version:p.version},{now});const n=db.prepare('SELECT count(*) n FROM appointment_events WHERE appointment_id=?').get(a.id).n;assert.equal(d.changeAppointment(f.id,a.id,{status:'cancelled',version:p.version},{now}).version,c.version);assert.equal(db.prepare('SELECT count(*) n FROM appointment_events WHERE appointment_id=?').get(a.id).n,n);assert.equal(d.checkSlot(f.id,f.s.id,date,'10:00',{now}).ok,true);});
test('public change policy rejects late reschedule/cancel and terminal status',()=>{const f=fixture(),a=d.createAppointment(f.id,request(f),{now});for(const b of [{status:'cancelled'},{date:nextDate,time:'10:00'}])throws(()=>d.changeAppointment(f.id,a.id,{...b,version:1},{publicRequest:true,now:new Date(date+'T07:00:00Z')}),'change_window_closed');throws(()=>d.changeAppointment(f.id,a.id,{status:'completed',version:1},{publicRequest:true,now}),'forbidden');throws(()=>d.changeAppointment(f.id,a.id,{status:'completed',version:1},{now}),'appointment_not_started');});
test('management bearer tokens are appointment scoped, authenticated and not guessable',()=>{const f=fixture(),g=fixture(),a=d.createAppointment(f.id,request(f),{now}),token=d.manageToken(f.id,a.id);assert.equal(d.fromToken(token).booking.id,a.id);throws(()=>d.fromToken(token.slice(0,-1)+'!'),'not_found');throws(()=>d.appointment(g.id,a.id),'not_found');});
test('manual payments count receipts and refunds without fabricated billing or duplicate receipt',()=>{const f=fixture(),a=d.createAppointment(f.id,request(f),{now}),body={appointmentId:a.id,amount:50,kind:'deposit',method:'cash',idempotencyKey:'payment_'+count};const p=d.recordPayment(f.id,body);assert.equal(d.recordPayment(f.id,body).id,p.id);assert.equal(d.appointment(f.id,a.id).paidAmount,50);throws(()=>d.recordPayment(f.id,{...body,amount:60}),'idempotency_conflict');throws(()=>d.recordPayment(f.id,{...body,amount:301,idempotencyKey:'too_much_'+count}),'payment_exceeds_booking_value');throws(()=>d.recordPayment(f.id,{...body,kind:'refund',amount:51,idempotencyKey:'refund_1_'+count}),'refund_exceeds_payments');d.recordPayment(f.id,{...body,kind:'refund',amount:20,idempotencyKey:'refund_2_'+count});assert.equal(d.appointment(f.id,a.id).paidAmount,30);});
test('notification mock never claims delivery and honors opt-out at processing time',()=>{const f=fixture(),a=d.createAppointment(f.id,request(f,{whatsappOptIn:true}),{now});d.setOptIn(f.id,a.customerId,false);d.processMockNotifications(new Date(nextMonday.getTime()-12*36e5));const rows=db.prepare('SELECT * FROM notification_outbox WHERE appointment_id=?').all(a.id);assert(rows.length>=1);assert(rows.every(r=>r.status==='blocked'));assert(rows.every(r=>r.reason==='opt_in_required'));assert(rows.every(r=>!['sent','delivered'].includes(r.status)));});
test('customer recognition is normalized and tenant scoped',()=>{const f=fixture(),g=fixture();const a=d.upsertCustomer(f.id,{name:'Customer',phone:'0820000000'}),b=d.upsertCustomer(f.id,{name:'Updated',phone:'+27 82 000 0000'}),c=d.upsertCustomer(g.id,{name:'Other tenant',phone:'27820000000'});assert.equal(a.id,b.id);assert.notEqual(a.id,c.id);assert.equal(b.name,'Updated');});
test.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true});});
