const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),{spawnSync}=require('child_process'),Database=require('better-sqlite3');
test('pre-pilot database upgrade is additive, repeatable, retains records and does not silently enable modular booking',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bd-old-schema-')),file=path.join(dir,'old.db'),db=new Database(file);
 db.exec(`CREATE TABLE clients(id TEXT PRIMARY KEY,salon TEXT NOT NULL,owner TEXT NOT NULL,email TEXT NOT NULL UNIQUE,phone TEXT,city TEXT,password_hash TEXT NOT NULL,whatsapp_enabled INTEGER NOT NULL DEFAULT 1,greeting TEXT,plan_status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL);
 CREATE TABLE services(id TEXT PRIMARY KEY,client_id TEXT NOT NULL,name TEXT NOT NULL,price INTEGER NOT NULL,duration_mins INTEGER NOT NULL DEFAULT 60,created_at TEXT NOT NULL);
 CREATE TABLE appointments(id TEXT PRIMARY KEY,client_id TEXT NOT NULL,customer_name TEXT NOT NULL,customer_phone TEXT,service_name TEXT NOT NULL,starts_at TEXT NOT NULL,duration_mins INTEGER NOT NULL DEFAULT 60,status TEXT NOT NULL DEFAULT 'confirmed',source TEXT NOT NULL DEFAULT 'manual',created_at TEXT NOT NULL);
 INSERT INTO clients VALUES('old','Existing Salon','Existing Owner','existing@example.invalid','27820000000','Johannesburg','fixture-password-hash-only',1,'Existing greeting','active','2026-01-01T00:00:00Z');
 INSERT INTO services VALUES('old-service','old','Existing Service',450,90,'2026-01-01T00:00:00Z');
 INSERT INTO appointments VALUES('old-appointment','old','Existing Customer','27820000001','Existing Service','2026-10-05T10:00:00',90,'confirmed','whatsapp','2026-01-01T00:00:00Z');`);
 const snapshot={client:db.prepare('SELECT * FROM clients').get(),service:db.prepare('SELECT * FROM services').get(),appointment:db.prepare('SELECT * FROM appointments').get()};db.close();
 for(let i=0;i<2;i++){const r=spawnSync(process.execPath,['-e',"const d=require('./db'); console.log(d.pragma('integrity_check')[0].integrity_check);d.close()"],{cwd:path.resolve(__dirname,'..'),env:{...process.env,DB_PATH:file},encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/ok/);}
 const checked=new Database(file);for(const [kind,table]of[['client','clients'],['service','services'],['appointment','appointments']]){const current=checked.prepare('SELECT * FROM '+table).get();for(const [key,value]of Object.entries(snapshot[kind]))assert.equal(current[key],value,table+'.'+key);}
 assert.equal(checked.prepare('SELECT count(*) n FROM schema_migrations').get().n,2);assert.equal(checked.prepare('SELECT count(*) n FROM salon_settings').get().n,0);assert.equal(checked.prepare('SELECT count(*) n FROM notification_outbox').get().n,0);assert.equal(checked.prepare('SELECT count(*) n FROM payments').get().n,0);assert.deepEqual(checked.pragma('foreign_key_check'),[]);checked.close();fs.rmSync(dir,{recursive:true,force:true});
});
