const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),net=require('net'),{spawn}=require('child_process');const Database=require('better-sqlite3');
const root=path.resolve(__dirname,'..');const future=new Date(Date.now()+7*864e5);while(future.getUTCDay()!==1)future.setUTCDate(future.getUTCDate()+1);const bookingDate=future.toISOString().slice(0,10);let base,child,db,dir,cookie,otherCookie,adminCookie,salon,service,staff,quote,booked;
async function api(method,url,body,c){const res=await fetch(base+'/api/v1'+url,{method,headers:{'Content-Type':'application/json',...(c?{Cookie:c}:{}),Origin:base},body:body===undefined?undefined:JSON.stringify(body)});return{status:res.status,data:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};}
test.before(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'bd-mod-http-'));const srv=net.createServer();await new Promise(r=>srv.listen(0,'127.0.0.1',r));const port=srv.address().port;await new Promise(r=>srv.close(r));base='http://127.0.0.1:'+port;const dbPath=path.join(dir,'fixture.db');child=spawn(process.execPath,['--require',path.join(__dirname,'network-mocks.cjs'),'server.js'],{cwd:root,env:{PATH:process.env.PATH,NODE_ENV:'test',PORT:String(port),DB_PATH:dbPath,JWT_SECRET:'only-test-modular-http-jwt-secret-32',ADMIN_PASSCODE:'only-test-admin-passphrase'},stdio:['ignore','pipe','pipe']});let log='';child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);let ready=false;for(let i=0;i<200;i++){if(child.exitCode!==null)throw Error(log);try{if((await fetch(base+'/healthz')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,30));}assert(ready,log);db=new Database(dbPath);});
test.after(async()=>{db?.close();if(child&&child.exitCode===null){child.kill();await new Promise(r=>child.once('exit',r));}fs.rmSync(dir,{recursive:true,force:true});});
test('signup/login creates trial, keeps public booking closed until configured, isolates auth roles',async()=>{let r=await api('POST','/auth/signup',{name:'Owner',salonName:'Lumiere QA',email:'QA@Example.invalid',password:'fake-test-password-12'});assert.equal(r.status,201);cookie=r.cookie;salon=r.data.salon;assert.equal(salon.bookingEnabled,false);assert.equal((await api('GET','/subscription',undefined,cookie)).data.status,'trial');assert.equal((await api('GET','/public/salons/'+salon.slug)).status,404);assert.equal((await api('GET','/session')).status,401);assert.equal((await api('GET','/platform/salons',undefined,cookie)).status,401);r=await api('POST','/auth/signup',{name:'Other',salonName:'Other QA',email:'other@example.invalid',password:'fake-test-password-12'});otherCookie=r.cookie;assert.equal((await api('POST','/auth/login',{email:'qa@example.invalid',password:'wrong'})).status,401);assert.equal((await api('POST','/auth/login',{email:'QA@EXAMPLE.INVALID',password:'fake-test-password-12'})).status,200);});
test('owner configures qualified services and staff; tenant foreign mutations rejected',async()=>{staff=(await api('GET','/staff',undefined,cookie)).data[0];let r=await api('POST','/services',{name:'Cut',price:250,durationMins:60,depositAmount:50,staffIds:[staff.id]},cookie);assert.equal(r.status,201);service=r.data;assert.equal((await api('PATCH','/services/'+service.id,{name:'Attack'},otherCookie)).status,404);assert.equal((await api('PATCH','/staff/'+staff.id,{name:'Attack'},otherCookie)).status,404);r=await api('PATCH','/salon',{phone:'0820000000',bookingEnabled:true,onboarded:true},cookie);assert.equal(r.status,200);assert.equal(r.data.phone,'27820000000');const pub=(await api('GET','/public/salons/'+salon.slug)).data;assert.equal(pub.services.length,1);assert(!('email'in pub.staff[0]));assert(!('email'in pub.salon));});
test('public availability and quote require explicit confirmation and are idempotent',async()=>{const publicPath='/public/salons/'+salon.slug;const slots=await api('GET',publicPath+'/availability?serviceId='+service.id+'&date='+bookingDate);assert.equal(slots.status,200);assert(slots.data.slots.length>0);const r=await api('POST',publicPath+'/quotes',{serviceId:service.id,staffId:'any',date:bookingDate,time:'10:00',customerName:'Public Guest',customerPhone:'0820000001',customerEmail:'guest@example.invalid',whatsappOptIn:true});assert.equal(r.status,201);quote=r.data;assert.equal(quote.summary.staffName,staff.name);assert.equal(quote.summary.depositAmount,50);assert.equal(db.prepare('SELECT count(*) n FROM appointments').get().n,0);assert.equal((await api('POST',publicPath+'/bookings',{quoteId:quote.quoteId,idempotencyKey:'public-request-001'})).status,400);let result=await api('POST',publicPath+'/bookings',{quoteId:quote.quoteId,confirmed:true,idempotencyKey:'public-request-001'});assert.equal(result.status,201);booked=result.data;result=await api('POST',publicPath+'/bookings',{quoteId:quote.quoteId,confirmed:true,idempotencyKey:'public-request-001'});assert.equal(result.data.booking.id,booked.booking.id);assert.equal(db.prepare('SELECT count(*) n FROM appointments').get().n,1);});
test('owner reschedule availability excludes only a tenant-owned existing appointment',async()=>{
 const query='/availability?serviceId='+service.id+'&staffId='+staff.id+'&date='+bookingDate;
 const ordinary=await api('GET',query,undefined,cookie);
 assert.equal(ordinary.status,200);
 assert(!ordinary.data.slots.some(s=>s.time==='10:15'));
 const own=await api('GET',query+'&appointmentId='+booked.booking.id,undefined,cookie);
 assert.equal(own.status,200);
 assert(own.data.slots.some(s=>s.time==='10:15'));
 assert.equal((await api('GET',query+'&appointmentId='+booked.booking.id,undefined,otherCookie)).status,404);
 assert.equal((await api('GET',query+'&appointmentId=missing',undefined,cookie)).status,404);
});
test('token management, atomic reschedule retry, owner receipts, customer history, mock notifications',async()=>{const token=booked.manageToken;let r=await api('GET','/public/bookings/'+token);assert.equal(r.status,200);assert.equal(r.data.booking.customerEmail,'guest@example.invalid');assert.equal((await api('GET','/public/bookings/'+token+'x')).status,404);const body={date:bookingDate,time:'11:00',staffId:staff.id,version:1,confirmed:true};r=await api('POST','/public/bookings/'+token+'/reschedule',body);assert.equal(r.status,200);assert.equal(r.data.booking.version,2);r=await api('POST','/public/bookings/'+token+'/reschedule',body);assert.equal(r.status,200);assert.equal(r.data.booking.version,2);r=await api('POST','/payments',{appointmentId:booked.booking.id,amount:50,kind:'deposit',method:'cash',reference:'In-person receipt',idempotencyKey:'deposit-payment-001'},cookie);assert.equal(r.status,201);assert.equal((await api('POST','/payments',{appointmentId:booked.booking.id,amount:1,kind:'payment',method:'cash',idempotencyKey:'attack-payment-001'},otherCookie)).status,404);r=await api('GET','/dashboard',undefined,cookie);assert.equal(r.data.metrics.collectedRevenue,50);assert.equal(r.data.metrics.appointmentValue,250);assert.equal(r.data.metrics.depositsRecorded,50);const customers=(await api('GET','/customers?search=Guest',undefined,cookie)).data;assert.equal(customers.length,1);assert.equal((await api('GET','/customers/'+customers[0].id,undefined,cookie)).data.bookings.length,1);assert.equal((await api('GET','/customers/'+customers[0].id,undefined,otherCookie)).status,404);r=await api('GET','/messages',undefined,cookie);assert(r.data.some(m=>m.status==='mock_ready'));assert(r.data.every(m=>!['sent','delivered'].includes(m.status)));assert.equal((await api('GET','/integrations/whatsapp',undefined,cookie)).data.liveNotificationsEnabled,false);});
test('legacy modular cancellation participates in event outbox and service archive preserves history',async()=>{const eventsBefore=db.prepare('SELECT count(*) n FROM appointment_events WHERE appointment_id=?').get(booked.booking.id).n;let r=await fetch(base+'/api/client/appointments/'+booked.booking.id+'/cancel',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,200);const a=(await api('GET','/bookings/'+booked.booking.id,undefined,cookie)).data;assert.equal(a.status,'cancelled');assert.equal(a.version,3);assert.equal(db.prepare('SELECT count(*) n FROM appointment_events WHERE appointment_id=?').get(a.id).n,eventsBefore+1);r=await fetch(base+'/api/client/services/'+service.id,{method:'DELETE',headers:{Cookie:cookie,'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,200);assert.equal(db.prepare('SELECT active FROM services WHERE id=?').get(service.id).active,0);assert.equal((await api('GET','/bookings/'+a.id,undefined,cookie)).data.serviceId,service.id);});
test('platform admin has separate session and changes are auditable without owner impersonation',async()=>{const login=await fetch(base+'/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({passcode:'only-test-admin-passphrase'})});adminCookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await api('GET','/session',undefined,adminCookie)).status,401);assert.equal((await api('GET','/platform/salons',undefined,adminCookie)).data.length,2);assert.equal((await api('PATCH','/platform/salons/'+salon.id+'/subscription',{status:'payment_failed',reason:'Fixture status only'},adminCookie)).status,200);assert.equal((await api('GET','/subscription',undefined,cookie)).data.automaticChargesEnabled,false);const audit=(await api('GET','/platform/audit',undefined,adminCookie)).data;assert(audit.some(x=>x.action==='subscription_updated'));assert.equal((await api('GET','/platform/audit',undefined,cookie)).status,401);});


test('retired public URLs never serve old markup; pilot documents require the correct session', async()=>{
 for(const url of ['/pilot','/pilot/','/','/login','/platform','/signup']) {
  const res=await fetch(base+url);assert.equal(res.status,200);assert.match(res.headers.get('cache-control'),/no-store/);
  const html=await res.text();assert.match(html,/src="\/ui.js"/);assert.doesNotMatch(html,/view-site|view-client|AI Receptionist|signupModal/);
 }
 for(const [url,next] of [['/pilot/controls','/login?next=photo-pilot'],['/pilot/controls/','/login?next=photo-pilot'],['/pilot/admin','/platform?next=pilot-admin'],['/pilot/admin/','/platform?next=pilot-admin']]){
  for(const token of ['', 'bd_client=invalid', url.includes('admin')?cookie:adminCookie]) {
   const res=await fetch(base+url,{redirect:'manual',headers:token?{Cookie:token}:{}});assert.equal(res.status,302);assert.equal(res.headers.get('location'),next);assert.match(res.headers.get('cache-control'),/no-store/);assert.doesNotMatch(await res.text(),/view-site|view-client/);
  }
 }
 for(const [url,token] of [['/pilot/controls',cookie],['/pilot/admin',adminCookie]]){
  const res=await fetch(base+url,{headers:{Cookie:token}});assert.equal(res.status,200);assert.match(res.headers.get('cache-control'),/no-store/);const html=await res.text();assert.match(html,/noindex, nofollow/);assert.match(html,/photoEstimatesPanel/);assert.doesNotMatch(html,/view-site|signupModal|\bAI\b|Claude|artificial intelligence/i);
 }
 for(const url of ['/index.html','/server.js','/ai.js','/db.js','/package.json','/SOURCE-CHANGES.patch','/pilot/index.html','/pilot/unknown'])assert.equal((await fetch(base+url)).status,404,url);
 assert.equal((await fetch(base+'/api/client/me')).status,401);assert.equal((await fetch(base+'/api/admin/inquiries')).status,401);
});

test('revoked client sessions cannot read private pilot markup',async()=>{
 const clientId=db.prepare('SELECT client_id FROM salon_settings WHERE slug=?').get(salon.slug).client_id;
 db.prepare('UPDATE clients SET auth_version=auth_version+1 WHERE id=?').run(clientId);
 const res=await fetch(base+'/pilot/controls',{redirect:'manual',headers:{Cookie:cookie}});assert.equal(res.status,302);assert.equal(res.headers.get('location'),'/login?next=photo-pilot');
 assert.equal((await api('GET','/session',undefined,cookie)).status,401);
});
