/* Optional browser integration QA. Run with RUN_BROWSER_UI=1 and PLAYWRIGHT_MODULE pointing to an installed
 * Playwright module and CHROMIUM_PATH if its bundled Chromium is unavailable.
 * All HTTP traffic is localhost; fixture database and credentials are disposable. */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),net=require('net'),{spawn}=require('child_process');
let playwright;try{playwright=require(process.env.PLAYWRIGHT_MODULE||'playwright');}catch{}
const root=path.resolve(__dirname,'..');
test('modular browser flows, mobile layout and stale-request safeguards',{skip:!playwright||process.env.RUN_BROWSER_UI!=='1',timeout:120000},async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bd-mod-ui-'));let child,browser;const screenshots=process.env.UI_SCREENSHOT_DIR;if(screenshots)fs.mkdirSync(screenshots,{recursive:true});
 t.after(async()=>{await browser?.close();if(child&&child.exitCode===null){child.kill();await new Promise(r=>child.once('exit',r));}fs.rmSync(dir,{recursive:true,force:true});});
 const server=net.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;await new Promise(r=>server.close(r));const base='http://127.0.0.1:'+port;
 child=spawn(process.execPath,['--require',path.join(__dirname,'network-mocks.cjs'),'server.js'],{cwd:root,env:{PATH:process.env.PATH,NODE_ENV:'test',PORT:String(port),DB_PATH:path.join(dir,'fixture.db'),JWT_SECRET:'disposable-browser-test-jwt-secret-32',ADMIN_PASSCODE:'disposable-browser-admin'},stdio:['ignore','pipe','pipe']});let log='';child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);let ready=false;for(let i=0;i<200;i++){if(child.exitCode!==null)throw Error(log);try{if((await fetch(base+'/healthz')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,30));}assert(ready,log);
 browser=await playwright.chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());
 const go=async p=>{await page.goto(base+p);};const click=a=>page.locator(`[data-action="${a}"]`).first().click();const form=id=>page.locator('#'+id);const save=id=>form(id).locator('[type=submit]').click();const gone=()=>page.locator('.modal').waitFor({state:'detached'});const shot=async name=>{if(screenshots)await page.screenshot({path:path.join(screenshots,name+'.png'),fullPage:true});};
 const json=async p=>{const r=await page.request.get(base+'/api/v1'+p);assert(r.ok(),await r.text());return r.json();};
 let salon,service,staff;
 await t.test('homepage WhatsApp example is responsive, keyboard-accessible and cannot send messages',async()=>{
  const writes=[];const onRequest=request=>{if(!['GET','HEAD','OPTIONS'].includes(request.method()))writes.push(request.url());};page.on('request',onRequest);
  for(const width of [320,390,768,1440]){
   await page.setViewportSize({width,height:1000});await go('/');
   assert.equal(await page.locator('.preview-card').evaluate(el=>getComputedStyle(el).transform),'none');
   assert.equal(await page.locator('.floating-note').evaluate(el=>getComputedStyle(el).transform),'none');
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'homepage overflow at '+width);
   const demo=page.locator('#whatsapp-demo');await page.getByRole('link',{name:'See WhatsApp demo',exact:true}).click();await page.waitForURL('**/#whatsapp-demo');
   await demo.scrollIntoViewIfNeeded();assert(await demo.isVisible());
   assert.match(await demo.locator('figcaption').textContent(),/No message is sent and no appointment is booked/);
   await page.locator('.whatsapp-photo-note summary').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.whatsapp-photo-note').getAttribute('open'),'');
   await shot('whatsapp-demo-'+width);
  }
  assert.deepEqual(writes,[]);page.off('request',onRequest);
  await page.locator('.bd-shortcuts-toggle').click();await page.getByRole('link',{name:'Photo pilot',exact:true}).click();await page.waitForURL('**/login?next=%2Fpilot');await page.locator('#auth-form').waitFor();assert.equal(await page.locator('#view-site').count(),0);
  await page.goBack();await page.locator('.hero').waitFor();await page.setViewportSize({width:1440,height:1000});
 });
 await t.test('all public pilot bookmarks, direct URLs and reloads use the current public design',async()=>{
  for(const [old,target] of [['/pilot','/login?next=%2Fpilot'],['/pilot/','/login?next=%2Fpilot'],['/pilot#pricing','/'],['/pilot/#whatsapp','/'],['/pilot#/client','/login?next=photo-pilot'],['/pilot/#cl-whatsapp','/login?next=photo-pilot'],['/pilot#/admin','/platform?next=pilot-admin'],['/pilot/#adm-inquiries','/platform?next=pilot-admin']]){
   await go(old);await page.waitForURL(base+target);await page.locator('#main').waitFor();await page.reload();await page.locator('#main').waitFor();
   assert.equal(await page.locator('#view-site, #signupModal, #client-login, #admin-login').count(),0);
   assert.doesNotMatch(await page.locator('body').innerText(),/\bAI\b|Claude|artificial intelligence/i);
  }
  await go('/');await page.locator('.bd-shortcuts-toggle').click();await page.getByRole('link',{name:'Photo pilot',exact:true}).click();await page.waitForURL('**/login?next=%2Fpilot');await page.getByRole('link',{name:'Back to BeautyDesk',exact:true}).first().click();await page.waitForURL(base+'/');await page.locator('.hero').waitFor();
  await page.goBack();await page.waitForURL('**/login?next=%2Fpilot');await page.locator('#auth-form').waitFor();await page.goForward();await page.locator('.hero').waitFor();
 });
 await t.test('owner signup, onboarding, service and staff create/edit, customer CRUD',async()=>{
  await go('/');await shot('marketing-desktop');await go('/signup');await form('auth-form').locator('[name=name]').fill('Local Owner');await page.locator('[name=salonName]').fill('Lumiere Browser QA');await page.locator('[name=email]').fill('browser@example.invalid');await page.locator('[name=password]').fill('local-browser-only-password');await save('auth-form');await page.waitForURL('**/onboarding');await page.getByText('Let’s make it yours.').waitFor();await shot('onboarding-desktop');salon=(await json('/session')).salon;assert.equal(salon.bookingEnabled,false);
  await go('/services');await click('new-service');await form('service-form').locator('[name=name]').fill('Signature cut');await form('service-form').locator('[name=price]').fill('250');await form('service-form').locator('[name=depositAmount]').fill('50');await save('service-form');await gone();await page.getByText('Signature cut',{exact:true}).first().waitFor();service=(await json('/services'))[0];
  await click('edit-service');await form('service-form').locator('[name=description]').fill('A carefully considered cut');await save('service-form');await gone();assert.equal((await json('/services'))[0].description,'A carefully considered cut');
  await go('/staff');await click('edit-staff');await form('staff-form').locator('[name=name]').fill('Avery Stylist');await form('staff-form').locator('[name=serviceIds]').check();await save('staff-form');await gone();staff=(await json('/staff'))[0];assert.equal(staff.name,'Avery Stylist');assert.equal(staff.serviceIds.length,1);
  await click('new-staff');await form('staff-form').locator('[name=name]').fill('Second Stylist');await form('staff-form').locator('[name=serviceIds]').check();await save('staff-form');await gone();assert.equal((await json('/staff')).length,2);
  await go('/customers');await click('new-customer');await form('customer-form').locator('[name=name]').fill('Synthetic Customer');await form('customer-form').locator('[name=phone]').fill('0820000011');await save('customer-form');await gone();await page.getByText('Synthetic Customer',{exact:true}).waitFor();await click('view-customer');await click('edit-current-customer');await form('customer-form').locator('[name=notes]').fill('Local QA note');await save('customer-form');await gone();assert.equal((await json('/customers'))[0].notes,'Local QA note');
  await go('/settings');await page.locator('[name=bookingEnabled]').check();await save('salon-form');await page.getByText('Salon details saved',{exact:true}).waitFor();assert.equal((await json('/session')).salon.bookingEnabled,true);
 });
 await t.test('authenticated modern photo workspace retains session and withheld ON, with gated legacy support',async()=>{
  await go('/dashboard');await page.getByRole('link',{name:'Photo pilot',exact:true}).click();await page.waitForURL('**/pilot');await page.locator('#photo-settings-form').waitFor();assert.equal(await page.locator('#view-site').count(),0);assert.equal(await page.locator('[name=photoEstimatesEnabled]').isDisabled(),true);assert.match(await page.locator('#main').textContent(),/Photo analysis is off/);assert.equal(await page.locator('input[type=file]').count(),0);
  await page.getByRole('link',{name:/Open support tools/}).click();await page.waitForURL('**/pilot/controls');await page.locator('#client-dash').waitFor();assert.equal(await page.locator('#client-login').isVisible(),false);assert.equal(await page.locator('#photoEstimatesToggle').isDisabled(),true);await page.goBack();await page.waitForURL('**/pilot');await page.locator('#photo-settings-form').waitFor();
 });
 await t.test('pilot login continuation, Back to site, browser history, logout and admin access',async()=>{
  const context=await browser.newContext({viewport:{width:390,height:844}});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());
  try{
   await p.goto(base+'/pilot/controls');await p.waitForURL('**/login?next=photo-pilot');await p.locator('[name=email]').fill('browser@example.invalid');await p.locator('[name=password]').fill('local-browser-only-password');await p.locator('#auth-form [type=submit]').click();await p.waitForURL('**/pilot/controls');await p.locator('#client-dash').waitFor();
   assert.doesNotMatch(await p.locator('body').innerText(),/\bAI\b|Claude|artificial intelligence/i);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
   await p.getByRole('link',{name:'Back to site',exact:false}).last().click();await p.waitForURL(base+'/');await p.locator('.hero').waitFor();await p.goBack();await p.waitForURL('**/pilot/controls');await p.locator('#client-dash').waitFor();await p.reload();await p.locator('#client-dash').waitFor();await p.goForward();await p.locator('.hero').waitFor();
   await p.goto(base+'/pilot/controls');await p.locator('#client-dash').waitFor();await p.getByRole('button',{name:'Log out',exact:true}).click();await p.waitForURL('**/login?next=photo-pilot');await p.goBack();await p.locator('.hero').waitFor();assert.equal(await p.locator('#client-dash').count(),0);await p.goto(base+'/pilot/controls');await p.waitForURL('**/login?next=photo-pilot');
   await p.goto(base+'/pilot#/admin');await p.waitForURL('**/platform?next=pilot-admin');await p.locator('[name=passcode]').fill('disposable-browser-admin');await p.locator('#platform-login-form [type=submit]').click();await p.waitForURL('**/pilot/admin');await p.locator('#admin-dash').waitFor();assert.doesNotMatch(await p.locator('body').innerText(),/\bAI\b|Claude|artificial intelligence/i);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
   await p.getByRole('link',{name:'Back to site',exact:false}).last().click();await p.waitForURL(base+'/');await p.locator('.hero').waitFor();await p.goto(base+'/platform');await p.getByRole('link',{name:'Pilot administration'}).waitFor();await p.getByRole('link',{name:'Pilot administration'}).click();await p.locator('#admin-dash').waitFor();await p.getByRole('button',{name:'Log out',exact:true}).click();await p.waitForURL('**/platform?next=pilot-admin');
  }finally{await context.close();}
 });
 await t.test('Cancel, Close, Escape, focus return and Back/Forward',async()=>{
  await go('/services');const before=(await json('/services')).length;await click('new-service');await form('service-form').locator('[name=name]').fill('Must not save');await page.getByRole('button',{name:'Cancel',exact:true}).click();await gone();assert.equal((await json('/services')).length,before);assert.equal(await page.locator('[data-action=new-service]').evaluate(e=>e===document.activeElement),true);
  await click('new-service');await page.getByRole('button',{name:'Close dialog'}).click();await gone();await click('new-service');await page.keyboard.press('Escape');await gone();await page.locator('a[data-nav][href="/customers"]').first().click();await page.waitForURL('**/customers');await page.goBack();await page.waitForURL('**/services');await page.locator('[data-action=new-service]').waitFor();await page.goForward();await page.waitForURL('**/customers');await page.locator('[data-action=new-customer]').waitFor();
 });
 await t.test('repeated submit sends one request and stale save cannot close a newer modal',async()=>{
  await go('/services');let count=0,release;const gate=new Promise(r=>release=r);await page.route('**/api/v1/services',async route=>{if(route.request().method()!=='POST')return route.continue();count++;const response=await route.fetch();await gate;await route.fulfill({response});});await click('new-service');await form('service-form').locator('[name=name]').fill('Delayed service');await form('service-form').evaluate(f=>{f.requestSubmit();f.requestSubmit();});await page.waitForTimeout(150);await page.getByRole('button',{name:'Close dialog'}).click();await click('new-service');await form('service-form').locator('[name=name]').fill('Unsaved next service');release();await page.waitForTimeout(200);assert.equal(count,1);assert.equal(await form('service-form').locator('[name=name]').inputValue(),'Unsaved next service');await page.keyboard.press('Escape');await page.unroute('**/api/v1/services');
 });
 const future=new Date(Date.now()+7*864e5);while(future.getUTCDay()!==1)future.setUTCDate(future.getUTCDate()+1);const date=future.toISOString().slice(0,10);
 async function toPublicDate(){await go('/book/'+salon.slug);await page.locator(`[data-action=choose-service][data-id="${service.id}"]`).click();await click('booking-next');await page.locator(`[data-action=choose-staff][data-id="${staff.id}"]`).click();await click('booking-next');await page.locator('#public-date').fill(date);await page.locator('[data-action=choose-time]').first().waitFor();}
 await t.test('public booking, Back, explicit summary, repeated confirm, management cancellation',async()=>{
  await toPublicDate();await click('choose-time');await click('booking-next');await form('public-details-form').locator('[name=customerName]').fill('Public Synthetic');await form('public-details-form').locator('[name=customerPhone]').fill('0820000012');await save('public-details-form');await form('public-confirm-form').waitFor();assert.equal((await json('/bookings')).length,0);await click('booking-back');assert.equal(await form('public-details-form').locator('[name=customerName]').inputValue(),'Public Synthetic');await save('public-details-form');await form('public-confirm-form').waitFor();await shot('booking-summary-desktop');await form('public-confirm-form').evaluate(f=>{f.requestSubmit();f.requestSubmit();});await page.getByText('You’re booked in.').waitFor();assert.equal((await json('/bookings')).length,1);await page.getByRole('link',{name:'View or manage my appointment'}).click();await click('manage-cancel');await save('manage-cancel-form');await gone();assert.equal((await json('/bookings'))[0].status,'cancelled');
 });
 await t.test('availability and customer-profile results cannot overwrite navigation or a newer modal',async()=>{
  await toPublicDate();let release;const gate=new Promise(r=>release=r);await page.route('**/api/v1/public/salons/*/availability?*',async route=>{const response=await route.fetch();await gate;await route.fulfill({response});});await page.locator('#public-date').fill(new Date(future.getTime()+864e5).toISOString().slice(0,10));await page.locator('.public-header a').click();await page.waitForURL(base+'/');release();await page.waitForTimeout(200);assert.equal(await page.locator('.hero').count(),1);await page.unroute('**/api/v1/public/salons/*/availability?*');
  await go('/customers');let releaseCustomer;const customerGate=new Promise(r=>releaseCustomer=r);await page.route('**/api/v1/customers/*',async route=>{const response=await route.fetch();await customerGate;await route.fulfill({response});});await click('view-customer');await page.getByRole('button',{name:'Close dialog'}).click();await click('new-customer');releaseCustomer();await page.waitForTimeout(200);assert.equal(await form('customer-form').count(),1);await page.keyboard.press('Escape');await page.unroute('**/api/v1/customers/*');
 });
 await t.test('mobile screens fit viewport and mobile navigation works',async()=>{
  await page.setViewportSize({width:390,height:844});for(const [url,name] of [['/','marketing-mobile'],['/signup','signup-mobile'],['/dashboard','dashboard-mobile'],['/calendar','calendar-mobile'],['/services','services-mobile'],['/book/'+salon.slug,'booking-mobile']]){await go(url);await page.waitForTimeout(100);await shot(name);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' must not overflow horizontally');}
  await go('/services');await click('menu');await page.locator('.sidebar a[href="/staff"]').click();await page.waitForURL('**/staff');await page.locator('[data-action=new-staff]').waitFor();await click('new-staff');await shot('staff-modal-mobile');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.keyboard.press('Escape');assert.deepEqual(errors,[]);
 });
});

// These deterministic regressions run without a browser and exercise the shipped
// frontend functions, not a second implementation of their request guards.
const vm=require('node:vm');
function uiHarness(){
 const nodes=new Map(),listeners={};let handler=async()=>({});
 const makeNode=()=>({innerHTML:'',textContent:'',style:{},dataset:{},children:[],classList:{add(){},remove(){}},isConnected:true,focus(){},querySelector(){return null},querySelectorAll(){return []}});
 for(const id of ['#app','#modal-root','#toast'])nodes.set(id,makeNode());
 const doc={activeElement:null,body:{style:{}},querySelector:s=>nodes.get(s)||null,querySelectorAll:()=>[],addEventListener:(k,fn)=>listeners[k]=fn};
 const context={console,Intl,URLSearchParams,Date,Math,JSON,Promise,Error,Number,String,Object,Array,Set,encodeURIComponent,decodeURIComponent,crypto:{randomUUID:()=>String(Math.random())},FormData:class{constructor(form){this.values=form.values||[];}[Symbol.iterator](){return this.values[Symbol.iterator]();}},setTimeout:()=>0,clearTimeout(){},document:doc,location:{pathname:'/',origin:'http://localhost'},history:{pushState(){},replaceState(){}},window:{scrollTo(){},addEventListener(){}},fetch:async(url,opts)=>{const data=await handler(url,opts);return {ok:true,status:200,json:async()=>data};}};
 const source=fs.readFileSync(path.join(root,'ui.js'),'utf8').replace(/renderRoute\(\);\s*\}\)\(\);\s*$/, 'globalThis.ui={S,runForm,modal,closeModal,customerDetail,loadPublicSlots,renderPublicBooking,renderRoute,refresh,loadOwnerSlots};})();');vm.createContext(context);vm.runInContext(source,context);
 return {ui:context.ui,nodes,doc,context,listeners,request(fn){handler=fn},makeNode};
}
function publicFixture(){return {salon:{name:'Synthetic salon',slug:'synthetic',timezone:'Africa/Johannesburg'},services:[{id:'svc',name:'Cut',durationMins:60,price:250}],staff:[{id:'staff',name:'Avery',serviceIds:['svc']}],step:0,serviceId:'svc',staffId:'staff',date:'2026-12-01',slots:[]};}
test('public booking renders enabled server response without private bookingEnabled flag',()=>{const h=uiHarness();h.ui.S.booking=publicFixture();assert.match(h.ui.renderPublicBooking(),/Choose your service/);assert.doesNotMatch(h.ui.renderPublicBooking(),/Online bookings are paused/);h.ui.S.booking.salon.bookingEnabled=false;assert.match(h.ui.renderPublicBooking(),/Online bookings are paused/);});
test('availability response cannot overwrite a route reached while request was pending',async()=>{const h=uiHarness();h.ui.S.booking={...publicFixture(),step:2};let release;h.request(()=>new Promise(r=>release=r));const work=h.ui.loadPublicSlots();h.ui.S.navId++;h.nodes.get('#app').innerHTML='new route';release({slots:[{time:'10:00',staffId:'staff'}]});await work;assert.equal(h.nodes.get('#app').innerHTML,'new route');});
test('customer profile response cannot replace a newer modal, nor reopen after Close',async()=>{for(const reopen of [false,true]){const h=uiHarness();let release;h.request(()=>new Promise(r=>release=r));const work=h.ui.customerDetail('customer');h.ui.closeModal();if(reopen)h.ui.modal('New customer','Unsent form');const expected=h.nodes.get('#modal-root').innerHTML;release({customer:{name:'Old result',phone:'0820000001'},bookings:[]});await work;assert.equal(h.nodes.get('#modal-root').innerHTML,expected);}});
test('form request is single-flight and response cannot update a disconnected form',async()=>{const h=uiHarness(),button=h.makeNode(),error=h.makeNode(),form=h.makeNode();button.innerHTML='Save';form.querySelector=s=>s==='[type=submit]'?button:error;form.querySelectorAll=()=>[button];let release,requests=0,effects=0;h.request(()=>{requests++;return new Promise(r=>release=r)});const callback=async(v,f,api)=>{await api('/services',{method:'POST',body:{name:'Test'}});effects++;};const work=h.ui.runForm(form,callback);await h.ui.runForm(form,callback);assert.equal(requests,1);form.isConnected=false;button.isConnected=false;release({id:'saved'});await work;assert.equal(effects,0);assert.equal(error.textContent,'');});
test('form response cannot redirect after navigation; connected successful form finishes once',async()=>{for(const navigate of [false,true]){const h=uiHarness(),button=h.makeNode(),error=h.makeNode(),form=h.makeNode();button.innerHTML='Save';form.querySelector=s=>s==='[type=submit]'?button:error;form.querySelectorAll=()=>[button];let release,effects=0;h.request(()=>new Promise(r=>release=r));const work=h.ui.runForm(form,async(v,f,api)=>{await api('/auth/signup',{method:'POST',body:{}});effects++;});if(navigate)h.ui.S.navId++;release({});await work;assert.equal(effects,navigate?0:1);assert.equal(button.disabled,false);assert.equal(button.innerHTML,'Save');}});

test('refresh after a save cannot discard a newer modal or navigation',async()=>{for(const changed of ['modal','route']){const h=uiHarness();let release;h.request(()=>new Promise(r=>release=r));const work=h.ui.refresh();if(changed==='modal')h.ui.modal('New form','Unsaved content');else h.ui.S.navId++;h.nodes.get('#app').innerHTML='Current view';release({user:{id:'u'},salon:{name:'Fixture'}});await work;assert.equal(h.nodes.get('#app').innerHTML,'Current view');if(changed==='modal')assert.match(h.nodes.get('#modal-root').innerHTML,/Unsaved content/);}});

test('owner reschedule availability excludes the edited appointment only',async()=>{for(const id of ['', 'appointment-1']){const h=uiHarness(),form=h.makeNode(),slot=h.makeNode();form.dataset.id=id;form.elements={serviceId:{value:'svc'},staffId:{value:'staff'},date:{value:'2026-12-01'},slot};h.nodes.set('#booking-form',form);h.nodes.set('#slot-note',h.makeNode());let url;h.request(request=>{url=request;return {slots:[]};});await h.ui.loadOwnerSlots();const params=new URL(url,'http://localhost').searchParams;assert.equal(params.get('appointmentId'),id||null);}});
